### ISSUE TITLE
libc is outdated

### ISSUE THREAD

**Issue by jkcclemens** [robo9k/rust-magic-sys#9]
The libc dependency that magic-sys uses is very outdated and has invalid definitions. This makes it incredibly difficult to use magic-sys on ARM systems. See [this build log](http://sprunge.us/OBQg) to see an example (`i8` vs `u8`).

**Comment by robo9k** [comment]
I've updated the `libc` dependency to current latest version `0.2.13` and published version `0.2.0` of `magic-sys`, please give it a try.

**Comment by jkcclemens** [comment]
Thank you very much!
